env_vars:
  - "DB_HOST=host.docker.internal"
  - "DB_USER=testuser"
  - "DB_PASSWORD=testpassword"
  - "DB_PORT=5432"
  - "DB_NAME=testdatabase"
  - "ENV_MODE=release"
  - "APP_PORT=8080"
  - "JWT_SECRET=secret"
  - "EMAIL_FROM="
  - "SMTP_HOST=smtp.gmail.com"
  - "SMTP_PORT=587"
  - "SMTP_USER="
  - "SMTP_PASSWORD="
