apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-cors
  namespace: default 
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "HEAD"
    accessControlAllowOriginList:
      - "*"
    accessControlAllowHeaders:
      - "*"
    accessControlMaxAge: 1728000
    addVaryHeader: true