apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path