- hosts: backend
  become: yes
  vars:
    docker_compose_project: /opt  # Directory for Docker Compose project files

  tasks:
    - name: Copy Prometheus configuration file
      copy:
        src: ../server-2/prometheus.yml
        dest: "{{ docker_compose_project }}/prometheus.yml"

    - name: Copy Docker Compose file
      copy:
        src: ../server-2/docker-compose.yml
        dest: "{{ docker_compose_project }}/docker-compose.yml"

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_project }}"
        state: absent

    - name: Start Docker Compose services
      community.docker.docker_compose_v2:
        project_src: "{{ docker_compose_project }}"
        state: present
      register: compose_output

    - name: Show Docker Compose results
      ansible.builtin.debug:
        var: compose_output
