- hosts: backend
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    - name: Copy Docker Compose
      copy:
        src: ./server2/docker-compose.yml
        dest: /opt/docker-compose.yml
    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/
